version: 2
general:
  branches:
    only:
      - branch-0.1.0-rc6
    ignore:
      - master
jobs:
  build:
    environment:
      REGISTRY: banzaicloud
    working_directory: ~/kubefed
    docker:
      - image: docker:17.05.0-ce-git
      - image: banzaicloud/golang:1.13

    steps:
      - checkout

      - deploy:
          name: Push docker images
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            make push
