# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

orbs:
  helm: banzaicloud/helm@0.0.3

workflows:
  version: 2

  helm-chart:
    jobs:
      - helm/lint-chart:
          chart-path: charts/kubefed
          filters:
            tags:
              ignore: /.*/

      - helm/publish-chart:
          context: helm
          chart-path: charts/kubefed
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /chart\/kubefed\/\d+.\d+.\d+/
