# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1
orbs:
  helm: banzaicloud/helm@v0.0.3

workflows:
  helm-chart-lint:
    jobs:
      - helm/lint-chart:
          charts-dir: charts
          filters:
            tags:
              ignore: /.*/
  helm-chart-release:
    jobs:
      - helm/publish-chart:
          context: helm
          charts-dir: charts
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /chart\/kubefed\/\d+.\d+.\d+/
